### ISSUE TITLE
OAuth issue

### ISSUE THREAD

**Issue by dima72** [Alfresco/alfresco-oauth-sample#1]
I'm writing Desktop application for integration with Alfresco.

callback address is : http://localhost:8181/oauthsample/mycallback.html
and I'm running local HTTP server in my application.
Java VM installed on client host.

on get request:
https://api.alfresco.com/auth/oauth/versions/2/authorize?client_id='+ App.Key +'&redirect_uri=http%3A%2F%2Flocalhost%3A8181%2Foauthsample%2Fmycallback.html&scope=public_api&response_type=code'
I get OAuth form with login and password.

But since I input valid login and password, I'm getting web page with message - Authentication failed

Could it be just administrative issue with my account being frozen by Alfresco or I'm doing something wrong?

Thank you in advance,
dmitry

**Comment by covolution** [comment]
OAuth is only available in Alfresco Cloud (so not if you have Alfresco running locally) and you need to have registered for a developer account.  Have you done that? https://www.alfresco.com/develop/cloud/signup

**Comment by dima72** [comment]
Dear Alfresco developer,

yes, I have registered  for developer account.

please check my login - konnov72@gmail.com
application name - syncovery
callback url -  http://localhost:8181/oauthsample/mycallback.html

I'm trying to access AlfrescoCloud, I have no alfresco installed locally.

1) I'm running local Web server with  https://github.com/Alfresco/alfresco-oauth-sample  is setup in local directory and webserver listening localhost:8181 

2) my application asks WebBrowser to go to address GET request to:
URL =  'https://api.alfresco.com/auth/oauth/versions/2/authorize?client_id='+ App.Key +'&redirect_uri=http%3A%2F%2Flocalhost%3A8181%2Foauthsample%2Fmycallback.html&scope=public_api&response_type=code';

 like this: ShellExecute(0,'open',PChar(URL),nil,nil,SW_NORMAL);

3) In WebBrowser I can see prompt page returned by AlfrescoCloud, please see attached picture.

4) I'm imputing  my login(  konnov72@gmail.com  )  and my password on authentication page and press Allow.

5) in this moment I'm getting Alfresco's web page - authentication failed. (please see second picture )

Please advice on the problem,

Thank you for collaboration with me on this problem,

Respectfully,
Dmitry Konnov
https://www.syncovery.com/   Cloud synchronization tool.

**Comment by dima72** [comment]
Dear Covolution,

if you can reproduce my problem on your local host and need access to my account,
I will provide you my password.

Respectfully,
Dmitry

**Comment by dima72** [comment]
maybe you can provide API keys and login credentials for testing purpose,
I can create desktop test case with Indy Webserver embedded, to show the problem. 
thanks in advance,
Dmitry

**Comment by covolution** [comment]
You should have 2 login credentials. a) for the developer portal and b) for login to https://my.alfresco.com (cloud).  When the oauth pops up you need to enter your credentials for b). 

I am probably not the best person to help you, I don't have a login to the developer portal to check your setttings.  Perhaps @ohej will be off more help?

**Comment by dima72** [comment]
> You should have 2 login credentials. a) for the developer portal and b) for login to  https://my.alfresco.com (cloud).  When the oauth pops up you need to enter your credentials for b). 
> I am probably not the best person to help you, I don't have a login to the developer portal to check your setttings.  Perhaps  @ohej will be off more help?

Dear Covolution, thank you for your help!  When I input credentials of   https://my.alfresco.com   it works!  In other words, if login to my.alfresco.com is successful then browser is
redirected to localhost/mycallback.html  and I can get tokens.

Respectfully, 
Dmitry

**Comment by dima72** [comment]
issue solved,
thanks

**Comment by edulima** [comment]
Hi I am using the alfresco cloud login credentials but I can't login. Any ideas guys?

**Comment by dima72** [comment]
me too. they seems to discontinued free membership.
