### ISSUE TITLE
REST get list of fliles

### ISSUE THREAD

**Issue by dima72** [Alfresco/alfresco-oauth-sample#2]
I can get list of containers like this:

GET https://api.alfresco.com/..companyName.../public/alfresco/versions/1/sites/..user../containers
How can i get list of files in container?
thanks,

**Comment by covolution** [comment]
If you are working with files then you should use CMIS. http://docs.alfresco.com/5.0/pra/1/topics/cmis-welcome.html

**Comment by dima72** [comment]
thank you for the suggestion, I got big XML document with files listed and heavily described in XML. But there so complicated structures. Is there way to get response in JSON and have only minimum of metadata for files listed in folder?

thanks in advance.
