### ISSUE TITLE
DELETE file remains Zero length in cloud

### ISSUE THREAD

**Issue by dima72** [Alfresco/alfresco-oauth-sample#4]
Dear All,

If I do DELETE http request to
https://api.alfresco.com/'+ CompanyName +'/public/cmis/versions/1.0/atom/content?id='+FileGuid

request comes through smoothly!  but file on remote is NOT deleted but becomes Zero length!

please suggest on how to remove file or move it to trash.

thanks in advance,

**Comment by jottley** [comment]
This is a bit easier to respond to as I already have an example: http://jared.ottleys.net/alfresco/alfresco-cmis-browser-binding-delete/

On Jul 24, 2015, at 10:48 AM, Dmitry Konnov <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear All,

If I do DELETE http request to
https://api.alfresco.com/'+ CompanyName +'/public/cmis/versions/1.0/atom/content?id='+FileGuid

request comes through smoothly! but file on remote is NOT deleted but becomes Zero length!

please suggest on how to remove file or move it to trash.

thanks in advance,

**Comment by dima72** [comment]
Thank you Maesto!,

call like https://api.alfresco.com/ottleys.net/public/cmis/versions/1.1/browser/root?cmisaction=delete&objectId=804f6300-38cd-48a4-86db-499f58497ae5;1.0

works fine. Can you please suggest what means ';1.0' at the end. In my case everything works only if i use pure GUID without ';1.0' 

thanks,

**Comment by jottley** [comment]
The 1.0 is there version number.  The CMIS objectId’s are made up of two parts the the GUID and the version number.  This is Alfresco specific.  Other CMIS repositories may build their CMIS objectId’s differently and at some point the alfresco one’s may change as well.  So the best practice is to get the CMIS ObjectId first before passing it in a call.

On Jul 25, 2015, at 1:27 AM, Dmitry Konnov <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you Maesto!,

call like https://api.alfresco.com/ottleys.net/public/cmis/versions/1.1/browser/root?cmisaction=delete&objectId=804f6300-38cd-48a4-86db-499f58497ae5;1.0

works fine. Can you please suggest what means ';1.0' at the end. In my case everything works only if i use pure GUID without ';1.0'

thanks,

**Comment by dima72** [comment]
yes, but
 In my case everything works only if i use pure GUID without ';1.0'

why my storage configuration does not recognize ';1.0' suffix. I just care about compatibility with other accounts.

**Comment by jottley** [comment]
The key is to use the objectId returned from any previous call whether or not it has the suffix.
