### ISSUE TITLE
cmis:value for cmis:description

### ISSUE THREAD

**Issue by dima72** [Alfresco/alfresco-oauth-sample#6]
Dear All,

I'm getting list of documents by GET http request:

https://api.alfresco.com/'+ CompanyName +'/public/cmis/versions/1.0/atom/children?id='+FolderId;

thus  cmis:value for cmis:description of listed files is not returned and requires additional
request for each document.

Is there way to tell Alfresco Cloud to fetch cmis:value for cmis:description of all chills requested?

thanks,

**Comment by jottley** [comment]
A request like https://api.alfresco.com/ottleys.net/public/cmis/versions/1.1/browser/root/sites/jared-ottleys-net/documentlibrary?succinct=true will return cmis:description for all of the children of the folder.

On Jul 28, 2015, at 1:39 PM, Dmitry Konnov <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear All,

I'm getting list of documents by GET http request:

https://api.alfresco.com/'+ CompanyName +'/public/cmis/versions/1.0/atom/children?id='+FolderId;

thus cmis:value for cmis:description of listed files is not returned and requires additional
request for each document.

Is there way to tell Alfresco Cloud to fetch cmis:value for cmis:description of all chills requested?

thanks,

**Comment by dima72** [comment]
Thank you!
it works fine!
