### ISSUE TITLE
API plan limit exceeded

### ISSUE THREAD

**Issue by dima72** [Alfresco/alfresco-oauth-sample#8]
Dear All,

what might be a reason for the below error?

HTTP ERROR 500: API plan limit exceeded'#$A#$A'Reason: Not Setl7xxe92c6ae1abf045fc85ec338418961bdd|1db2437af8b34992f57aedbb22fe27838f42d019|quota?ok|rate?failed|

thanks,

**Comment by ghost** [comment]
I think you need to login to https://developer.alfresco.com/dashboard/application, and place a request to upgrade your API plan from development to production.

**Comment by dima72** [comment]
Dear Seng,

you response came too late, we seems to drop support of Alfresco.
Please remind if Alfresco file storage is available publicly for free.

Respectfully,
Dmitry

**Comment by ghost** [comment]
The Alfresco Community version is open-source, free to install and host on your own, but does not come with paid Support service. Alfresco in the Cloud is no longer offer any free account sign up. 

https://www.alfresco.com/products/enterprise-content-management?utm_source=google&utm_medium=cpc&utm_content=Alfresco%20Community%20Download%20-%20MB&utm_campaign=Brand%20-%20Search&referrer=PPC&gclid=CKy79YWx3c4CFZVahgodFagP1g
